name: Deployment pipeline

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # BACKEND
      - name: Install backend dependencies
        working-directory: ./phonebook-backend
        run: npm install

      - name: Backend lint
        working-directory: ./phonebook-backend
        run: npm run lint

      - name: Backend test
        working-directory: ./phonebook-backend
        run: npm test

      # FRONTEND
      - name: Install frontend dependencies
        working-directory: ./phonebook-frontend
        run: npm install

      - name: Frontend lint
        working-directory: ./phonebook-frontend
        run: npm run lint

      - name: Frontend test
        working-directory: ./phonebook-frontend
        run: npm run test

      - name: Frontend build
        working-directory: ./phonebook-frontend
        run: npm run build
